services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./:/app

  db:
    image: postgres:17
    ports:
      - "5432:5432"
    env_file:
      .env
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U wagtail -d wagtail_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:
